
name = "begins-design-ai-api"
main = "src/index.ts"
compatibility_date = "2025-10-01"

# --- Bindings ---
[[r2_buckets]]
binding = "R2"
bucket_name = "begins-design-ai-bucket"
preview_bucket_name = "begins-design-ai-bucket"

[[d1_databases]]
binding = "DB"
database_name = "begins-design-ai"
database_id = "8e9de02e-8078-4f18-bc82-ce8f2c99b407"
preview_database_id = "8e9de02e-8078-4f18-bc82-ce8f2c99b407"

[vars]
ASSET_BASE = "https://begins-design-ai-bucket.alphaxmar.workers.dev"
ACCESS_AUD = "begins-design-ai-access-aud"
ACCESS_JWKS_URL = "https://alphaxmar.cloudflareaccess.com/cdn-cgi/access/certs"

[ai]
binding = "AI"
